version: '2'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - netStat
  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
     networks:
      - netStat
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: viajabara
networks:
  netStat:
    driver: bridge
